	// import styles from "@/styles/Home.module.css";
  import Head from "next/head";
  import Navbar from "@/components/Navbar";
  import Footer from "@/components/Footer";
  import { NextSeo } from "next-seo";
  import Button from "@/components/Button";
  import {
    Link as ScrollLink,
    animateScroll as scroll,
    scroller,
    Scroll,
  } from "react-scroll";
  import Link from "next/link";
  import Faq from "react-faq-component";
  import dataSide from "@/data/layanan/pmm/dataSide.json";
  import dataBenefitPMM from "@/data/layanan/pmm/dataBenefitPMM.json";
  import dataKelasPMM from "@/data/layanan/pmm/dataKelasPMM.json";
   
  import { PiToolboxFill } from "react-icons/pi";
  import { MdBook } from "react-icons/md";
  import { PiCertificateFill } from "react-icons/pi";
   
   
  // Import modul atau dependensi yang dibutuhkan
  import Card from "@/components/cards/Card";
  import Image from "next/image";
  import axios from "../../api/axios";
  import { BsCheckCircleFill } from "react-icons/bs";
  import { useAppContext } from "@/context/AppContext";
  import { FaArrowCircleRight } from "react-icons/fa";
  import Benefit1 from "@/images/layanan/pmm/benefit/benefit1.png";
  import Benefit2 from "@/images/layanan/pmm/benefit/benefit2.png";
  import Benefit3 from "@/images/layanan/pmm/benefit/benefit3.png";
   
  export default function LayananPendukung({ mitra, berita, testimoni }) {
    const [state, dispatch] = useAppContext();
    return (
      <>
        <NextSeo
          title="Platform Merdeka Mengajar - Solo Technopark"
          description="Sebagai Unit Pelaksana Teknis Daerah (UPTD) pada BALITBANGDA Kota Surakarta, berdasarkan Peraturan Walikota No. 15 Tahun 2022. Menerapkan Pola Tata Kelola Badan Layanan Umum Daerah (BLUD) berdasarkan Perwali Surakarta No. 38 Tahun 2022."
          canonical="https://solotechnopark.id/"
          openGraph={{
            url: "https://solotechnopark.id/",
            title: "Platform Merdeka Mengajar - solo technopark",
            description: "Kawasan Inovatif dan Berdaya Saing International.",
            images: [
              {
                url: "/favicon.png",
                width: 800,
                height: 600,
                alt: "Platform Merdeka Mengajar Solo Technopark",
              },
            ],
            site_name: "Platform Merdeka Mengajar - solotechnopark",
          }}
        />
   
        <Head>
          <title>Platform Merdeka Mengajar - Solotechnopark.id</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link
            rel="icon"
            href="https://solotechnopark.id/wp-content/uploads/2021/09/Solo-Tecno.png"
          />
        </Head>
        <Navbar />
   
        <main className="mt-20">
          <section className="bg-cam bg-cover bg-no-repeat">
            <div className="container">
              <div className="h-[90vh] flex flex-col justify-center">
                <h1 className="head-1 mb-5 max-w-3xl font-bold text-primary-100">
                {
                  state.isLang === 'ID' ? ' Platform Merdeka Mengajar ' : ' Independent Teaching Platform'
              }{" "}
                </h1>
                <h1 className="head-1 mb-5 max-w-3xl font-bold text-primary-100">
                {
                  state.isLang === 'ID' ? ' Solo Technopark ' : ' Solo Technopark '
              }{" "}
                </h1>
                
                <h3 className="mb-5 max-w-3xl text-primary">
                {
                  state.isLang === 'ID' ? ' Sebagai penunjang Implementasi Kurikulum Merdeka agar dapat membantu guru dalam mendapatkan referensi, inspirasi, dan pemahaman tentang Kurikulum Merdeka ' : ' As a support for the implementation of the Independent Curriculum, it can help teachers get references, inspiration and understanding of the Independent Curriculum'
              }{" "}
                </h3>
              </div>
            </div>
          </section>
          
          <section className="bg-white">
              <div className="container">
                  <div className="flex gap-10">
                      <div className="py-10">
                          <div className="py-24">
                              <ul className="list-none" style={{ maxWidth: "40rem" }}>
                                  {dataSide.pmm.map((data, i) => (
                                      <li key={i} className="head-3 mb-10 bg-primary-100 text-white">
                                          <ScrollLink className="cursor-pointer" to={data.path} smooth={true} duration={100} spy={true}>
                                              <p className="ml-5 my-2">{data.menu}</p>
                                              {data.submenu.map((item, i) => (
                                                  <li key={i} className="head-4 px-5 py-1 bg-white text-primary-100">
                                                      {item}
                                                  </li>
                                              ))}
                                          </ScrollLink>
                                      </li>
                                  ))}
                              </ul>
                          </div>
                      </div>
                    <div className="flex-1 py-10">
                      <div id="benefit" className="container pt-24">
                        <h2 className="head-2 mb-5 font-bold text-primary-100">Benefit</h2>
                        <div className="pb-10 pt-10">
                          <div className="flex flex-row space-x-10 text-justify">
                            <div className="bg-no-repeat bg-cover bg-origin-border bg-custom-1">
                              <div className="relative w-64 h-80 p-6 rounded-lg">
                                <div className="absolute -mt-20 left-1/3 -right-2 transform -translate-x-1/2">
                                  <Image src={Benefit1} alt="Icon" className="w-44 h-44" />
                                </div>
                                <div className="text-white mt-28">
                                  <h1 className="text-2xl font-bold">Training Kit</h1>
                                  <p className="text-xs mt-2">Sejumlah Paket komperhensif yang disesuaikan dengan
                                    kebutuhan individu atau kelompok, menjadikannya solusi yang sempurna untuk pelatihan,
                                    pengembangan diri, dan pengajaran yang efektif.</p>
                                </div>
                              </div>
                            </div>
                            <div className="bg-no-repeat bg-cover bg-origin-border bg-custom-2">
                              <div className="relative w-64 h-80 p-6 rounded-lg">
                                <div className="absolute -mt-20 left-1/3 -right-2 transform -translate-x-1/2">
                                  <Image src={Benefit2} alt="Icon" className="w-44 h-44" />
                                </div>
                                <div className="text-white mt-28">
                                  <h1 className="text-2xl font-bold">Modul Pelatihan</h1>
                                  <p className="text-xs mt-2">Modul dari pembimbing yang kompeten dan relevan dengan dunia
                                    industri, sehingga mudah difahami dan dapat di implementasikan antara teori dan
                                    praktiknya, mulai dari pemahaman dasar hingga bagaimana menguasai teknik untuk menjadi
                                    mekanik manufaktur yang profesional.</p>
                                </div>
                              </div>
                            </div>
                            <div className="bg-no-repeat bg-cover bg-origin-border bg-custom-3">
                              <div className="relative w-64 h-80 p-6 rounded-lg">
                                <div className="absolute -mt-20 left-1/3 -right-2 transform -translate-x-1/2">
                                  <Image src={Benefit3} alt="Icon" className="w-44 h-44" />
                                </div>
                                <div className="text-white mt-28">
                                  <h1 className="text-2xl font-bold">Sertifikat Kompetensi</h1>
                                  <p className="text-xs mt-2">Sertifikat kompetensi yang dapat digunakan untuk bekerja di
                                    industri Manufaktur.</p>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
   
                      <div id="basic" className="container pt-24">
                        <h2 className="head-2 mb-5 font-bold text-primary-100">Kelas Basic</h2>
                        <div className="pb-10 pt-10">
                          <div className="flex flex-wrap -mx-2 text-justify">
                            <div className="w-full md:w-1/2 lg:w-1/4 px-2 mb-4 flex">
                              <div
                                className="max-w-sm w-full rounded-xl shadow-lg overflow-hidden flex flex-col justify-between">
                                <div className="gradient-bg p-6 text-white rounded-t-xl">
                                  <h2 className="text-2xl font-bold">Mechanical Manufacture</h2>
                                </div>
                                <div className="p-5 bg-white flex-grow">
                                  <p className="text-red-500 font-semibold">Durasi : 9 Bulan</p>
                                  <p className="mt-4 text-gray-600">Pelatihan keterampilan bidang permesinan manufacturing
                                    untuk mengolah bahan baku menjadi produk jadi maupun setengah jadi (part) dengan
                                    output SDM yang kompeten yang mudah terserap di dunia industri.</p>
                                </div>
                                <div className="flex justify-end p-2">
                                  <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6 text-red-500" fill="none"
                                       viewBox="0 0 24 24" stroke="currentColor">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                          d="M17 8l4 4m0 0l-4 4m4-4H3" />
                                  </svg>
                                </div>
                              </div>
                            </div>
                            <div className="w-full md:w-1/2 lg:w-1/4 px-2 mb-4 flex">
                              <div
                                className="max-w-sm w-full rounded-xl shadow-lg overflow-hidden flex flex-col justify-between">
                                <div className="gradient-bg p-6 text-white rounded-t-xl">
                                  <h2 className="text-2xl font-bold">Design Manufacture</h2>
                                </div>
                                <div className="p-5 bg-white flex-grow">
                                  <p className="text-red-500 font-semibold">Durasi : 9 Bulan</p>
                                  <p className="mt-4 text-gray-600">Pelatihan keterampilan menggambar rancang bangun suatu
                                    produk yang memiliki presisi tinggi yang dikerjakan secara komputerisasi, dengan
                                    output SDM yang kompeten yang mudah terserap di dunia industri.</p>
                                </div>
                                <div className="flex justify-end p-2">
                                  <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6 text-red-500" fill="none"
                                       viewBox="0 0 24 24" stroke="currentColor">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                          d="M17 8l4 4m0 0l-4 4m4-4H3" />
                                  </svg>
                                </div>
                              </div>
                            </div>
                            <div className="w-full md:w-1/2 lg:w-1/4 px-2 mb-4 flex">
                              <div
                                className="max-w-sm w-full rounded-xl shadow-lg overflow-hidden flex flex-col justify-between">
                                <div className="gradient-bg p-6 text-white rounded-t-xl">
                                  <h2 className="text-2xl font-bold">Welding Manufacture</h2>
                                </div>
                                <div className="p-5 bg-white flex-grow">
                                  <p className="text-red-500 font-semibold">Durasi : 9 Bulan</p>
                                  <p className="mt-4 text-gray-600">Pelatihan keterampilan pengelasan yang mencakup
                                    pengetahuan dasar bahan logam, proses metalurgi, teknik serta teknologi pengelasan
                                    dengan output SDM yang kompeten yang mudah terserap di dunia industri.</p>
                                </div>
                                <div className="flex justify-end p-2">
                                  <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6 text-red-500" fill="none"
                                       viewBox="0 0 24 24" stroke="currentColor">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                          d="M17 8l4 4m0 0l-4 4m4-4H3" />
                                  </svg>
                                </div>
                              </div>
                            </div>
                            <div className="w-full md:w-1/2 lg:w-1/4 px-2 mb-4 flex">
                              <div
                                className="max-w-sm w-full rounded-xl shadow-lg overflow-hidden flex flex-col justify-between">
                                <div className="gradient-bg p-6 text-white rounded-t-xl">
                                  <h2 className="text-2xl font-bold">Automation Manufacture</h2>
                                </div>
                                <div className="p-5 bg-white flex-grow">
                                  <p className="text-red-500 font-semibold">Durasi : 9 Bulan</p>
                                  <p className="mt-4 text-gray-600">Pelatihan keterampilan rancang bangun perangkat dan
                                    sistem kontrol mencakup materi dasar dengan tujuan operasional otomatis melalui
                                    komputerisasi, dengan output SDM yang kompeten yang mudah terserap di dunia
                                    industri.</p>
                                </div>
                                <div className="flex justify-end p-2">
                                  <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6 text-red-500" fill="none"
                                       viewBox="0 0 24 24" stroke="currentColor">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                          d="M17 8l4 4m0 0l-4 4m4-4H3" />
                                  </svg>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
   
                      <div id="specialist" className="container pt-24">
                        <h2 className="head-2 mb-5 font-bold text-primary-100">Kelas Specialist</h2>
                        <div className="pb-10 pt-10">
                          <div className="flex flex-wrap -mx-2 text-justify">
                            <div className="w-full md:w-1/2 lg:w-1/4 px-2 mb-4 flex">
                              <div className="bg-white p-6 rounded-lg shadow-lg flex flex-col justify-between flex-grow">
                                <div className="mb-auto">
                                  <h2 className="text-xl font-bold text-red-600 mb-4">Design and CNC Specialist</h2>
                                  <p className="text-gray-600 mb-2">Durasi: 3,5 Bulan</p>
                                  <p className="text-gray-600 mb-4">Lorem ipsum dolor sit amet consectetur. Consequat
                                    viverra gravida elementum vulputate facilisis...</p>
                                </div>
                                <div className="mt-auto">
                                  <a href="#" className="text-red-600 hover:text-red-800">→</a>
                                </div>
                              </div>
                            </div>
                            <div className="w-full md:w-1/2 lg:w-1/4 px-2 mb-4 flex">
                              <div className="bg-white p-6 rounded-lg shadow-lg flex flex-col justify-between flex-grow">
                                <div className="mb-auto">
                                  <h2 className="text-xl font-bold text-red-600 mb-4">General Welding</h2>
                                  <p className="text-gray-600 mb-2">Durasi: 2,5 Bulan</p>
                                  <p className="text-gray-600 mb-4">Lorem ipsum dolor sit amet consectetur. Consequat
                                    viverra gravida elementum vulputate facilisis...</p>
                                </div>
                                <div className="mt-auto">
                                  <a href="#" className="text-red-600 hover:text-red-800">→</a>
                                </div>
                              </div>
                            </div>
                            <div className="w-full md:w-1/2 lg:w-1/4 px-2 mb-4 flex">
                              <div className="bg-white p-6 rounded-lg shadow-lg flex flex-col justify-between flex-grow">
                                <div className="mb-auto">
                                  <h2 className="text-xl font-bold text-red-600 mb-4">Underwater Welding</h2>
                                  <p className="text-gray-600 mb-2">Durasi: 2 Bulan & 2 Minggu</p>
                                  <p className="text-gray-600 mb-4">Lorem ipsum dolor sit amet consectetur. Consequat
                                    viverra gravida elementum vulputate facilisis...</p>
                                </div>
                                <div className="mt-auto">
                                  <a href="#" className="text-red-600 hover:text-red-800">→</a>
                                </div>
                              </div>
                            </div>
                            <div className="w-full md:w-1/2 lg:w-1/4 px-2 mb-4 flex">
                              <div className="bg-white p-6 rounded-lg shadow-lg flex flex-col justify-between flex-grow">
                                <div className="mb-auto">
                                  <h2 className="text-xl font-bold text-red-600 mb-4">Automation</h2>
                                  <p className="text-gray-600 mb-2">Durasi: 1 Bulan</p>
                                  <p className="text-gray-600 mb-4">Lorem ipsum dolor sit amet consectetur. Consequat
                                    viverra gravida elementum vulputate facilisis...</p>
                                </div>
                                <div className="mt-auto">
                                  <a href="#" className="text-red-600 hover:text-red-800">→</a>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
   
                    </div>
                  </div>
              </div>
          </section>
        </main>
        <Footer />
      </>
    );
  }
   
  export async function getServerSideProps() {
    try {
      const mitraResponse = await axios.get("mitra");
      const testimoniResponse = await axios.get("testimonial");
   
      const mitra = mitraResponse.data.data;
      const testimoni = testimoniResponse.data.data;
   
      return {
        props: {
          mitra,
          testimoni
        }
      };
    } catch (err) {
      console.warn(err);
      return {
        props: {
          mitra: [],
          berita: [],
          testimoni: []
        }
      };
    }
  }
   
  const data = {
    rows: [
      {
        title: "Jenis Diklat yang Bisa Diikuti",
        content:
          "<ul><li><b>Diklat APBN:</b><span style=\"font-weight: 400\"> Dibuka pada periode tertentu dan bebas biaya untuk seluruh warga indonesia</span></li><li><b>Diklat APBD:</b><span style=\"font-weight: 400\"> Dibuka pada periode tertentu dan bebas biaya untuk yang memiliki KTP Surakarta</span></li><li><b>Diklat Mandiri:</b><span style=\"font-weight: 400\"> Dibuka sepanjang tahun dan besaran biaya ditentukan sesuai dengan program yang diikuti </span></li></ul>"
      },
      {
        title: "Yang Dipelajari dalam Diklat",
        content:
          "<ul><li><span style=\"font-weight: 400\">Pelatihan hardskill sesuai dengan jurusan yang diambil</span></li><li><span style=\"font-weight: 400\">Belajar menggunakan berbagai jenis mesin manufaktur</span></li><li><span style=\"font-weight: 400\">Pelatihan softskill</span></li></ul>"
      },
      {
        title: "Penyaluran Kerja setelah Lulus Diklat",
        content:
          "Belum tentu. Penyaluran kerja menimbang aspek nilai akhir peserta diklat, usia peserta diklat, dan kebutuhan perusahaan mitra."
      },
      {
        title: "Tahapan saat Mengikuti Diklat",
        content:
          "<ul><li><span style=\"font-weight: 400\">Tahap 1 merupakan pendidikan dasar teknik (Basic). Dalam tahapan basic ini,para siswa diajarkan ilmu dasar yang meliputi Lathe Work,Bench Work,Grinding Work,Milling Work, dan Gambar Teknik.</span></li><li><span style=\"font-weight: 400\">Tahap 2 merupakan tahap lanjutan (Applied). Dalam tahapan lanjutan ( </span><i><span style=\"font-weight: 400\">Applied </span></i><span style=\"font-weight: 400\">), para siswa diajarkan ke tahap selanjutnya yakni seperti Otomasi Manufaktur, Desain Manufaktur, dan Mekanik Manufaktur.&nbsp;</span></li><li><span style=\"font-weight: 400\">Tahap 3 merupakan tahap akhir (Advance).&nbsp; Peserta yang berhasil lulus berhak mendapatkan Sertifikat Keahlian yang dikeluarkan oleh Solotechnopark.</span></li></ul>"
      },
      {
        title: "Durasi Pelaksanaan Diklat",
        content:
          "<ul><li><span style=\"font-weight: 400\">Secara umum diklat dilaksanakan minimal 6 bulan hingga tahap applied dan maksimal 9 bulan hingga tahap advanced</span></li><li><span style=\"font-weight: 400\">Apabila peserta mengikuti melalui program pemerintah maka durasi diklat didasarkan sesuai dengan kebijakan pemerintah</span></li></ul>"
      },
      {
        title: "Batas Usia untuk Mengikuti Diklat",
        content:
          "<ul><li><span style=\"font-weight: 400\">Tidak ada batasan usia</span></li><li><span style=\"font-weight: 400\">Apabila ingin langsung mendapat rekomendasi penyaluran kerja minimal berusia 22 tahun</span></li></ul>"
      },
      {
        title: "Persyaratan untuk Mengikuti Diklat",
        content: "Minimal memiliki ijazah SLTA dan sederajat"
      },
      {
        title: "Persyaratan Fisik untuk Mengikuti Diklat",
        content:
          "<ul><li><span style=\"font-weight: 400\">Tidak buta warna</span></li><li><span style=\"font-weight: 400\">Bukan penderita ayan/epilepsi</span></li></ul>"
      },
      {
        title: "Dokumen yang Harus Dipersiapkan",
        content:
          "<ul><li><span style=\"font-weight: 400\">Fotocopy KTP Calon Peserta</span></li><li><span style=\"font-weight: 400\">Fotocopy KTP Orangtua</span></li><li><span style=\"font-weight: 400\">Fotocopy KK</span></li><li><span style=\"font-weight: 400\">Fotocopy Ijasah</span></li><li><span style=\"font-weight: 400\">Fotocopy Transkrip Nilai</span></li><li><span style=\"font-weight: 400\">Surat Keterangan Sehat</span></li><li><span style=\"font-weight: 400\">Surat Pernyataan (Bermaterai) * Didapat saat registrasi offline</span></li><li><span style=\"font-weight: 400\">SKCK</span></li><li><span style=\"font-weight: 400\">Pas Foto 4X6</span></li></ul>"
      },
      {
        title: "Minimal Nilai Ijazah untuk Mendaftar Diklat",
        content: "Tidak ada"
      },
      {
        title: "Penggunaan Materai pada Dokumen Diklat",
        content:
          "Ya, pada dokumen Surat Penyataan *Didapat saat registrasi offline"
      },
      {
        title: "Alur Pendaftaran Diklat",
        content:
          "<ul><li><span style=\"font-weight: 400\">Datang ke Pendaftaran STP</span></li><li><span style=\"font-weight: 400\">Scan QR Code di Ruang Pendaftaran</span></li><li><span style=\"font-weight: 400\">Mengisi Formulir Biodata Offline</span></li><li><span style=\"font-weight: 400\">Melengkapi Berkas Persyaratan</span></li><li><span style=\"font-weight: 400\">Tes Tulis</span></li><li><span style=\"font-weight: 400\">Tes Wawancara</span></li></ul>"
      },
      {
        title: "Mendaftar untuk Banyak Jurusan Diklat",
        content: "Tidak bisa",
      },
      {
        title: "Warga di Luar Kota Surakarta Mengikuti Diklat",
        content: "Bisa",
      },
      {
        title: "Kuota Peserta Diklat",
        content:
          "Ada. Jumlahnya ditentukan tergantung program dan kebijakan Solo Technopark",
      },
      {
        title: "Biaya Pendaftaran Diklat",
        content:
          '<ul><li><span style="font-weight: 400">Bervariasi tergantung program</span></li><li><span style="font-weight: 400">Untuk lebih detail harap hubungi CP</span></li></ul>',
      },
    ],
  };