// import styles from "@/styles/Home.module.css";
import Head from "next/head";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { NextSeo } from "next-seo";
import Button from "@/components/Button";
import {
  Link as ScrollLink,
  animateScroll as scroll,
  scroller,
  Scroll,
} from "react-scroll";
import Link from "next/link";
import Faq from "react-faq-component";
import dataProfilAlumni from "@/data/layanan/teknis/dataProfilAlumni";
import dataSide from "@/data/layanan/teknis/dataSide.json";
import dataBenefitTeknis from "@/data/layanan/teknis/dataBenefitTeknis.json";
import dataMateriTeknis from "@/data/layanan/teknis/dataMateriTeknis.json";
import dataProspekTeknis from "@/data/layanan/teknis/dataProspekTeknis.json";

import AvatarOgsci from "@/images/layanan/teknis/avatar/avatarogsci.png";
import BenefitOgsci1 from "@/images/layanan/teknis/benefit/benefitogsci1.png";
import BenefitOgsci2 from "@/images/layanan/teknis/benefit/benefitogsci2.png";
import BenefitOgsci3 from "@/images/layanan/teknis/benefit/benefitogsci3.png";
import BenefitOgsci4 from "@/images/layanan/teknis/benefit/benefitogsci4.png";
import BenefitOgsci5 from "@/images/layanan/teknis/benefit/benefitogsci5.png";
import BenefitOgsci6 from "@/images/layanan/teknis/benefit/benefitogsci6.png";
import BenefitOgsci7 from "@/images/layanan/teknis/benefit/benefitogsci7.png";
import ProspekOgsci1 from "@/images/layanan/teknis/prospek/prospekogsci1.png";
import ProspekOgsci2 from "@/images/layanan/teknis/prospek/prospekogsci2.png";
import ProspekOgsci3 from "@/images/layanan/teknis/prospek/prospekogsci3.png";
import ProspekOgsci4 from "@/images/layanan/teknis/prospek/prospekogsci4.png";
import GaleriOgsci1 from "@/images/layanan/teknis/galeri/galeriogsci1.png";
import GaleriOgsci2 from "@/images/layanan/teknis/galeri/galeriogsci2.png";
import GaleriOgsci3 from "@/images/layanan/teknis/galeri/galeriogsci3.png";
import GaleriOgsci4 from "@/images/layanan/teknis/galeri/galeriogsci4.png";


// Import modul atau dependensi yang dibutuhkan
import Card from "@/components/cards/Card";
import Image from "next/image";
import axios from "../../api/axios";
import { BsCheckCircleFill } from "react-icons/bs";
import ProfilAlumni from "@/components/swiper/ProfilAlumni";
import { useAppContext } from "@/context/AppContext";
import { FaArrowCircleRight } from "react-icons/fa";

export default function LayananPendukung({ mitra, berita, testimoni }) {
  const [state, dispatch] = useAppContext();
  return (
    <>
      <NextSeo
        title="Oil and Gas Skill Center of Indonesia - Solo Technopark"
        description="Sebagai Unit Pelaksana Teknis Daerah (UPTD) pada BALITBANGDA Kota Surakarta, berdasarkan Peraturan Walikota No. 15 Tahun 2022. Menerapkan Pola Tata Kelola Badan Layanan Umum Daerah (BLUD) berdasarkan Perwali Surakarta No. 38 Tahun 2022."
        canonical="https://solotechnopark.id/"
        openGraph={{
          url: "https://solotechnopark.id/",
          title: "OGSCI - solo technopark",
          description: "Kawasan Inovatif dan Berdaya Saing International.",
          images: [
            {
              url: "/favicon.png",
              width: 800,
              height: 600,
              alt: "Oil and Gas Skill Center of Indonesia Solo Technopark",
            },
          ],
          site_name: "Oil and Gas Skill Center of Indonesia - solotechnopark",
        }}
      />

      <Head>
        <title>Oil and Gas Skill Center of Indonesia - Solotechnopark.id</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="https://solotechnopark.id/wp-content/uploads/2021/09/Solo-Tecno.png"
        />
      </Head>
      <Navbar />

      <main className="mt-20">
        <section className="bg-ogsci bg-cover bg-no-repeat">
          <div className="container">
            <div className="h-[90vh] flex flex-col justify-center">
              <h1 className="head-1 mb-5 max-w-3xl font-bold text-primary-100">
              {
                state.isLang === 'ID' ? ' Oil and Gas Skill Center of Indonesia ' : ' Oil and Gas Skill Center of Indonesia'
            }{" "}
              </h1>
              
              <h3 className="mb-5 max-w-3xl text-primary">
              {
                state.isLang === 'ID' ? ' Pelatihan keterampilan rancang bangun perangkat dan sistem kontrol mencakup materi dasar dengan tujuan operasional otomatis melalui komputerisasi, dengan output SDM yang kompeten yang mudah terserap di dunia industri ' : ' Training in device and control system design skills includes basic material with the aim of automated operations through computerization, with competent human resource output that is easily absorbed in the industrial world'
            }{" "}
              </h3>
              
              <Link
                className="inline-block"
                href={
                  "https://docs.google.com/forms/d/e/1FAIpQLSe5n7zk-RG2-tESLGzcDKKwLimXKU5HAkLkphECLkqXhD4adw/viewform"
                }
                target="_blank"
              >
                <Button className="bg-primary-100 text-white hover:opacity-50 hover:bg-white hover:text-primary-100">
                { state.isLang === 'ID' ? 'Pendaftaran' : 'Registration'}
                </Button>
              </Link>
              
              <Link
                className="inline-block"
                href={
                  "https://docs.google.com/forms/d/e/1FAIpQLSe5n7zk-RG2-tESLGzcDKKwLimXKU5HAkLkphECLkqXhD4adw/viewform"
                }
                target="_blank"
              >
                <Button className="text-white hover:opacity-50 hover:bg-white hover:text-primary-100">
                { state.isLang === 'ID' ? 'Share' : 'Share'}
                </Button>
              </Link>
            </div>
          </div>
        </section>
        
        <section className="bg-white">
            <div className="container py-20">
                <div className="flex">
                    <div className="">
                        <ul className="list-none">
                            {dataSide.ogsci.map((data, i) => (
                                <li key={i} className="head-3 my-10 bg-primary-100 text-white">
                                    <ScrollLink className="cursor-pointer" to={data.path} smooth={true} duration={100} spy={true}>
                                        <p className="ml-5 my-2">{data.menu}</p>
                                        {data.submenu.map((item, i) => (
                                            <li key={i} className="head-4 px-5 py-1 bg-white text-primary-100">
                                                {item}
                                            </li>
                                        ))}
                                    </ScrollLink>
                                </li>
                            ))}
                        </ul>
                    </div>
                    <div className="flex-1 pl-5 py-10">
                        <div id="benefit" className="container py-20">
                            <h2 className="head-2 mb-5 font-bold text-primary-100">Tentang OGSCI</h2>
                            <div className="flex py-10 gap-10">
                                <Image
                                  className="object-cover w-full h-full"
                                  src={AvatarOgsci}
                                  width={400}
                                  height={400}
                                  alt="avatarogsci"
                                />
                                <h4 className="mb-5 text-justify">
                                    Oil and Gas Skill Center of Indonesia (OGSCI) adalah sebuah program pelatihan yang diselenggarakan oleh Satuan Kerja Khusus Pelaksana Kegiatan Usaha Hulu Minyak dan Gas Bumi (SKK Migas) bekerja sama dengan Solo Technopark. Program ini bertujuan untuk memberikan fasilitas lengkap sebagai sarana sosialisasi, komunikasi, edukasi, dan informasi terkait industri hulu migas di Indonesia. Melalui pelatihan-pelatihan yang diselenggarakan di OGSCI, peserta akan mempelajari berbagai keterampilan dan teknik terkait industri hulu migas seperti electrical, instrument, mechanical, process operator, dan health and safety environment.Selain itu, program pelatihan OGSCI juga menawarkan pelatihan dibidang konstruksi dan manajemen proyek.
                                </h4>
                            </div>
                        </div>
                        
                        <div id="benefit" className="container py-20">
                            <h2 className="head-2 mb-5 font-bold text-primary-100">Benefit</h2>
                            <div className="pb-10">
                                <h4 className="mb-5 text-justify">
                                    Mengikuti pelatihan Oil and Gas Skills memberikan manfaat berupa pemahaman mendalam tentang industri minyak dan gas, peningkatan keterampilan teknis dalam eksplorasi, produksi, dan pemeliharaan fasilitas energi, serta peluang karir yang luas dalam sektor ini.
                                </h4>
                                <div className="grid grid-cols-1 lg:grid-cols-1 gap-2 lg:gap-2">
                                    <div className="grid grid-cols-1 lg:grid-cols-2 gap-2 lg:gap-2">
                                        {dataBenefitTeknis.ogsci &&
                                          dataBenefitTeknis.ogsci.map((data, i) => (
                                            <div key={i} className="grid grid-cols-1 lg:grid-cols-2">
                                                <Card
                                                  key={i}
                                                  className={
                                                    "p-2 gap-2 lg:mx-2 col-span-2 bg-grey"
                                                  }
                                                >   
                                                  <div>
                                                    {i === 0 && (
                                                        <Image
                                                          className="mx-auto"
                                                          src={BenefitOgsci1}
                                                          width={420}
                                                          height={420}
                                                          alt="icon"
                                                        />
                                                    )}
                                                    {i === 1 && (
                                                        <Image
                                                          className="mx-auto"
                                                          src={BenefitOgsci2}
                                                          width={420}
                                                          height={420}
                                                          alt="icon"
                                                        />
                                                    )}
                                                    {i === 2 && (
                                                        <Image
                                                          className="mx-auto"
                                                          src={BenefitOgsci3}
                                                          width={420}
                                                          height={420}
                                                          alt="icon"
                                                        />
                                                    )}
                                                    {i === 3 && (
                                                        <Image
                                                          className="mx-auto"
                                                          src={BenefitOgsci4}
                                                          width={420}
                                                          height={420}
                                                          alt="icon"
                                                        />
                                                    )}
                                                    {i === 4 && (
                                                        <Image
                                                          className="mx-auto"
                                                          src={BenefitOgsci5}
                                                          width={420}
                                                          height={420}
                                                          alt="icon"
                                                        />
                                                    )}
                                                    {i === 5 && (
                                                        <Image
                                                          className="mx-auto"
                                                          src={BenefitOgsci6}
                                                          width={420}
                                                          height={420}
                                                          alt="icon"
                                                        />
                                                    )}
                                                    {i === 6 && (
                                                        <Image
                                                          className="mx-auto"
                                                          src={BenefitOgsci7}
                                                          width={420}
                                                          height={420}
                                                          alt="icon"
                                                        />
                                                    )}
                                                  </div>
                                                  <div>
                                                    <h3
                                                      className="text-xl font-bold text-primary-100 mt-5 lg:mt-5 mb-5"
                                                    >
                                                      {data.title}
                                                    </h3>
                                                  </div>
                                                  <div>
                                                    <h4
                                                      className="text-justify mb-5"
                                                    >
                                                      {data.desc}
                                                    </h4>
                                                  </div>
                                                </Card>
                                              
                                            </div>
                                        ))}
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                        <div id="materi" className="container py-20">
                            <h2 className="head-2 mb-5 font-bold text-primary-100">Materi</h2>
                            <div className="pb-10">
                                <h4 className="mb-5 text-justify">
                                    Berikut materi yang akan di dapatkan selama pelaksanaan pelatihan di Solo Technopark:
                                </h4>
                                <div className="grid grid-cols-1 lg:grid-cols-1 gap-2 lg:gap-2">
                                    <div className="grid grid-cols-1 lg:grid-cols-1 gap-2 lg:gap-2">
                                        {dataMateriTeknis.ogsci &&
                                          dataMateriTeknis.ogsci.map((data, i) => (
                                            <div key={i} className="grid grid-cols-1 lg:grid-cols-2">
                                                <Card
                                                  key={i}
                                                  className={
                                                    "p-2 gap-2 lg:mx-2 col-span-2"
                                                  }
                                                >   
                                                  <div className="">
                                                    <h3
                                                      className="text-xl font-bold text-white text-center mt-5 lg:mt-5 mb-5 bg-primary-100 rounded-lg p-4"
                                                    >
                                                      {data.title}
                                                    </h3>
                                                  </div>
                                                  <div className="bg-grey rounded-lg p-4">
                                                    <h4
                                                      className="text-justify mb-5"
                                                    >
                                                      {data.desc}
                                                    </h4>
                                                  </div>
                                                </Card>
                                              
                                            </div>
                                        ))}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        {/* prospek */}
        <section className="bg-grey">
          <div id="prospek" className="container py-20">
            <h2 className="head-2 max-w-xl mt-10 mb-5 font-bold text-primary-100">
            { state.isLang === 'ID' ? 'Prospek Kerja' : 'Job Prospects'}
            </h2>
            <div className="grid grid-cols-1 lg:grid-cols-4 gap-2 lg:gap-2">
                {dataProspekTeknis.ogsci &&
                  dataProspekTeknis.ogsci.map((data, i) => (
                    <div key={i} className="grid grid-cols-1 lg:grid-cols-2">
                      {/* <Card
                        // key={i}
                        className={
                          "bg-gray-100 p-8 flex items-start gap-10 lg:mx-5 "
                        }
                      >
                      </Card> */}
                        
                        <Card
                          key={i}
                          className={
                            "p-8 gap-5 lg:mx-2 col-span-2"
                          }
                        >   
                          <div>
                            {i === 0 && (
                                <Image
                                  className="mx-auto"
                                  src={ProspekOgsci1}
                                  width={280}
                                  height={280}
                                  alt="icon"
                                />
                            )}
                            {i === 1 && (
                                <Image
                                  className="mx-auto"
                                  src={ProspekOgsci2}
                                  width={280}
                                  height={280}
                                  alt="icon"
                                />
                            )}
                            {i === 2 && (
                                <Image
                                  className="mx-auto"
                                  src={ProspekOgsci3}
                                  width={280}
                                  height={280}
                                  alt="icon"
                                />
                            )}
                            {i === 3 && (
                                <Image
                                  className="mx-auto"
                                  src={ProspekOgsci4}
                                  width={280}
                                  height={280}
                                  alt="icon"
                                />
                            )}
                          </div>
                          <div>
                            <h3
                              className="text-xl font-bold text-primary-100 mt-5 lg:mt-5 mb-5"
                              style={{ maxWidth: "14rem" }}
                            >
                              {data.title}
                            </h3>
                          </div>
                          <div>
                            <ul className="grid grid-cols-1 lg:grid-cols-1 gap-5">
                              {data.list.map((item, i) => (
                                <li key={i} className="flex gap-5">
                                  <BsCheckCircleFill className="text-primary-100" />
                                  <span className="text-gray-600">{item}</span>
                                </li>
                              ))}
                            </ul>
                          </div>
                        </Card>
                      
                    </div>
                  ))}
             </div>
          </div>
        </section>

        {/* image galery */}
        <section className="">
          <div id="galeri" className="container py-20">
            <h2 className="head-2 my-20 max-w-3xl mx-auto text-center font-bold text-primary-100">
            { state.isLang === 'ID' ? 'Galeri OGSCI' : 'OGSCI Gallery'}
            </h2>
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-5 lg:gap-10 mb-10">
              <div className="flex justify-center items-center bg-primary-gradient-x-100 rounded-3xl h-96 overflow-hidden">
                <Image
                  className="object-cover w-full h-full"
                  src={GaleriOgsci1}
                  width={540}
                  height={400}
                  alt="image head"
                />
              </div>
              <div className="flex justify-center items-center bg-primary-gradient-x-100 rounded-3xl h-96 overflow-hidden">
                <Image
                  className="object-cover w-full h-full"
                  src={GaleriOgsci2}
                  width={540}
                  height={400}
                  alt="image head"
                />
              </div>
              <div className="flex justify-center items-center bg-primary-gradient-x-100 rounded-3xl h-96 overflow-hidden">
                <Image
                  className="object-cover w-full h-full"
                  src={GaleriOgsci3}
                  width={540}
                  height={400}
                  alt="image head"
                />
              </div>
              <div className="flex justify-center items-center bg-primary-gradient-x-100 rounded-3xl h-96 overflow-hidden">
                <Image
                  className="object-cover w-full h-full"
                  src={GaleriOgsci4}
                  width={540}
                  height={400}
                  alt="image head"
                />
              </div>
            </div>
          </div>
        </section>

        <section className="">
          <div className="container py-20">
            <h2 className="head-2 my-20 max-w-3xl mx-auto text-center font-bold text-primary-100">
            { state.isLang === 'ID' ? 'Alumni' : 'Alumni'}
            </h2>
            <ProfilAlumni data={JSON.parse(dataProfilAlumni)} />
          </div>
        </section>        
      </main>
      <Footer />
    </>
  );
}

export async function getServerSideProps() {
  try {
    const mitraResponse = await axios.get("mitra");
    const testimoniResponse = await axios.get("testimonial");

    const mitra = mitraResponse.data.data;
    const testimoni = testimoniResponse.data.data;

    return {
      props: {
        mitra,
        testimoni,
      },
    };
  } catch (err) {
    console.warn(err);
    return {
      props: {
        mitra: [],
        berita: [],
        testimoni: [],
      },
    };
  }
}

const data = {
  rows: [
    {
      title: "Jenis Diklat yang Bisa Diikuti",
      content:
        '<ul><li><b>Diklat APBN:</b><span style="font-weight: 400"> Dibuka pada periode tertentu dan bebas biaya untuk seluruh warga indonesia</span></li><li><b>Diklat APBD:</b><span style="font-weight: 400"> Dibuka pada periode tertentu dan bebas biaya untuk yang memiliki KTP Surakarta</span></li><li><b>Diklat Mandiri:</b><span style="font-weight: 400"> Dibuka sepanjang tahun dan besaran biaya ditentukan sesuai dengan program yang diikuti </span></li></ul>',
    },
    {
      title: "Yang Dipelajari dalam Diklat",
      content:
        '<ul><li><span style="font-weight: 400">Pelatihan hardskill sesuai dengan jurusan yang diambil</span></li><li><span style="font-weight: 400">Belajar menggunakan berbagai jenis mesin manufaktur</span></li><li><span style="font-weight: 400">Pelatihan softskill</span></li></ul>',
    },
    {
      title: "Penyaluran Kerja setelah Lulus Diklat",
      content:
        "Belum tentu. Penyaluran kerja menimbang aspek nilai akhir peserta diklat, usia peserta diklat, dan kebutuhan perusahaan mitra.",
    },
    {
      title: "Tahapan saat Mengikuti Diklat",
      content:
        '<ul><li><span style="font-weight: 400">Tahap 1 merupakan pendidikan dasar teknik (Basic). Dalam tahapan basic ini,para siswa diajarkan ilmu dasar yang meliputi Lathe Work,Bench Work,Grinding Work,Milling Work, dan Gambar Teknik.</span></li><li><span style="font-weight: 400">Tahap 2 merupakan tahap lanjutan (Applied). Dalam tahapan lanjutan ( </span><i><span style="font-weight: 400">Applied </span></i><span style="font-weight: 400">), para siswa diajarkan ke tahap selanjutnya yakni seperti Otomasi Manufaktur, Desain Manufaktur, dan Mekanik Manufaktur.&nbsp;</span></li><li><span style="font-weight: 400">Tahap 3 merupakan tahap akhir (Advance).&nbsp; Peserta yang berhasil lulus berhak mendapatkan Sertifikat Keahlian yang dikeluarkan oleh Solotechnopark.</span></li></ul>',
    },
    {
      title: "Durasi Pelaksanaan Diklat",
      content:
        '<ul><li><span style="font-weight: 400">Secara umum diklat dilaksanakan minimal 6 bulan hingga tahap applied dan maksimal 9 bulan hingga tahap advanced</span></li><li><span style="font-weight: 400">Apabila peserta mengikuti melalui program pemerintah maka durasi diklat didasarkan sesuai dengan kebijakan pemerintah</span></li></ul>',
    },
    {
      title: "Batas Usia untuk Mengikuti Diklat",
      content:
        '<ul><li><span style="font-weight: 400">Tidak ada batasan usia</span></li><li><span style="font-weight: 400">Apabila ingin langsung mendapat rekomendasi penyaluran kerja minimal berusia 22 tahun</span></li></ul>',
    },
    {
      title: "Persyaratan untuk Mengikuti Diklat",
      content: "Minimal memiliki ijazah SLTA dan sederajat",
    },
    {
      title: "Persyaratan Fisik untuk Mengikuti Diklat",
      content:
        '<ul><li><span style="font-weight: 400">Tidak buta warna</span></li><li><span style="font-weight: 400">Bukan penderita ayan/epilepsi</span></li></ul>',
    },
    {
      title: "Dokumen yang Harus Dipersiapkan",
      content:
        '<ul><li><span style="font-weight: 400">Fotocopy KTP Calon Peserta</span></li><li><span style="font-weight: 400">Fotocopy KTP Orangtua</span></li><li><span style="font-weight: 400">Fotocopy KK</span></li><li><span style="font-weight: 400">Fotocopy Ijasah</span></li><li><span style="font-weight: 400">Fotocopy Transkrip Nilai</span></li><li><span style="font-weight: 400">Surat Keterangan Sehat</span></li><li><span style="font-weight: 400">Surat Pernyataan (Bermaterai) * Didapat saat registrasi offline</span></li><li><span style="font-weight: 400">SKCK</span></li><li><span style="font-weight: 400">Pas Foto 4X6</span></li></ul>',
    },
    {
      title: "Minimal Nilai Ijazah untuk Mendaftar Diklat",
      content: "Tidak ada",
    },
    {
      title: "Penggunaan Materai pada Dokumen Diklat",
      content:
        "Ya, pada dokumen Surat Penyataan *Didapat saat registrasi offline",
    },
    {
      title: "Alur Pendaftaran Diklat",
      content:
        '<ul><li><span style="font-weight: 400">Datang ke Pendaftaran STP</span></li><li><span style="font-weight: 400">Scan QR Code di Ruang Pendaftaran</span></li><li><span style="font-weight: 400">Mengisi Formulir Biodata Offline</span></li><li><span style="font-weight: 400">Melengkapi Berkas Persyaratan</span></li><li><span style="font-weight: 400">Tes Tulis</span></li><li><span style="font-weight: 400">Tes Wawancara</span></li></ul>',
    },
    {
      title: "Mendaftar untuk Banyak Jurusan Diklat",
      content: "Tidak bisa",
    },
    {
      title: "Warga di Luar Kota Surakarta Mengikuti Diklat",
      content: "Bisa",
    },
    {
      title: "Kuota Peserta Diklat",
      content:
        "Ada. Jumlahnya ditentukan tergantung program dan kebijakan Solo Technopark",
    },
    {
      title: "Biaya Pendaftaran Diklat",
      content:
        '<ul><li><span style="font-weight: 400">Bervariasi tergantung program</span></li><li><span style="font-weight: 400">Untuk lebih detail harap hubungi CP</span></li></ul>',
    },
  ],
};
